export const FETCH_NEWS_LIST = "FETCH_NEWS_LIST";
export const FETCH_NEWS_LIST_SUCCEDDED = "FETCH_NEWS_LIST_SUCCEDDED";
export const FETCH_NEWS_LIST_FAILED = "FETCH_NEWS_LIST_FAILED";

export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_SUCCEDDED = "FETCH_NEWS_SUCCEDDED";
export const FETCH_NEWS_FAILED = "FETCH_NEWS_FAILED";
